services:
  catalog-service:
    image: "ghcr.io/joelproxi/catalog-service"
    container_name: "catalog-service"
    depends_on:
      - postgres
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/catalog_db
      - SPRING_PROFILES_ACTIVE=testdata
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001


  postgres:
    image: "postgres:18-alpine"
    container_name: "book-postgres"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
